server.port = 5454

spring.datasource.url=jdbc:mysql://localhost:3306/stylistIQDb
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql: true

cloudinary.cloud_name = dasurdgfx
cloudinary.api_key = 213344594735547
cloudinary.api_secret = _bDTPnsQBYsQ4BK0b7E8wuKq-4k
cloudinary.folderPath = stylistiq/e-wardrobe
